[build]
  base = "src/frontend/kys-frontend"
  publish = "build"
  command = "npm ci --prefer-offline --no-audit && npm run build"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  GENERATE_SOURCEMAP = "false"
  CI = "false"
  SKIP_PREFLIGHT_CHECK = "true"
  PUBLIC_URL = "."
  BUILD_PATH = "build"
  REACT_APP_NODE_ENV = "production"
  DISABLE_ESLINT_PLUGIN = "true"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  REACT_APP_API_URL = "$REACT_APP_API_URL"
  REACT_APP_NODE_ENV = "production"
  REACT_APP_SUPABASE_URL = "$REACT_APP_SUPABASE_URL"
  REACT_APP_SUPABASE_ANON_KEY = "$REACT_APP_SUPABASE_ANON_KEY"

[context.deploy-preview.environment]
  REACT_APP_API_URL = "$REACT_APP_API_URL"
  REACT_APP_NODE_ENV = "development"
  REACT_APP_SUPABASE_URL = "$REACT_APP_SUPABASE_URL"
  REACT_APP_SUPABASE_ANON_KEY = "$REACT_APP_SUPABASE_ANON_KEY"

# DEPLOYMENT TRIGGER - 2025-01-01 14:33:00 UTC
# Fixed TypeScript types, package.json dependencies, and optimized build process
# Netlify deployment errors resolved - build should work now 