[build]
  base = "src/frontend/kys-frontend"
  publish = "build"
  command = "npm install && npm run build"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  REACT_APP_API_URL = "https://kademe-kys-production.up.railway.app/api"
  REACT_APP_NAME = "Kademe KYS"
  REACT_APP_VERSION = "1.0.0"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production]
  command = "npm install && npm run build"

[context.deploy-preview]
  command = "npm install && npm run build" 