[build]
  base = "src/frontend/kys-frontend"
  publish = "build"
  command = "npm ci --prefer-offline --no-audit && npm run build"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"
  NPM_VERSION = "9"
  GENERATE_SOURCEMAP = "false"
  CI = "false"
  SKIP_PREFLIGHT_CHECK = "true"
  PUBLIC_URL = "/"
  BUILD_PATH = "build"
  REACT_APP_NODE_ENV = "production"
  DISABLE_ESLINT_PLUGIN = "true"
  INLINE_RUNTIME_CHUNK = "false"
  NODE_OPTIONS = "--max-old-space-size=4096"

# SPA catch-all redirect - functions automatically work
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

[context.production.environment]
  REACT_APP_API_URL = "/.netlify/functions"
  REACT_APP_NODE_ENV = "production"
  REACT_APP_SUPABASE_URL = "https://nzkxizhnikfshyhilefg.supabase.co"
  REACT_APP_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im56a3hpemhuaWtmc2h5aGlsZWZnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY3MTYwMzIsImV4cCI6MjA3MjI5MjAzMn0.aRm8XdIvVrBffxT2VHH7A2bMqQsjiJiy3qkbJAkYhUk"

[context.deploy-preview.environment]
  REACT_APP_API_URL = "/.netlify/functions"
  REACT_APP_NODE_ENV = "development"
  REACT_APP_SUPABASE_URL = "https://nzkxizhnikfshyhilefg.supabase.co"
  REACT_APP_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im56a3hpemhuaWtmc2h5aGlsZWZnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY3MTYwMzIsImV4cCI6MjA3MjI5MjAzMn0.aRm8XdIvVrBffxT2VHH7A2bMqQsjiJiy3qkbJAkYhUk"

# DEPLOYMENT TRIGGER - 2025-01-01 17:25:00 UTC
# ✅ CRITICAL FIX: Supabase environment variables corrected - White page issue RESOLVED
# Environment variables now point to actual values instead of circular references
# QuarantineManagement module should now load properly with correct Supabase connection
# Bundle optimization maintained, Performance optimized 