[build]
  publish = "."
  command = "echo 'Static site, no build needed'"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/api/*"
  to = "https://web-production-3c77.up.railway.app/api/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  VITE_API_URL = "https://web-production-3c77.up.railway.app"
  NETLIFY_URL = "https://merry-dragon-924246.netlify.app"

[context.preview.environment]
  VITE_API_URL = "https://web-production-3c77.up.railway.app"
  NETLIFY_URL = "https://merry-dragon-924246.netlify.app"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable" 