[phases.build]
cmds = [
  "cd src/frontend/kys-frontend && npm install",
  "cd src/frontend/kys-frontend && GENERATE_SOURCEMAP=false npm run build",
  "cd src/backend && npm install",
  "cd src/backend && npm run build"
]

[phases.start]
cmd = "cd src/backend && npm start"

[variables]
NODE_ENV = "production"
GENERATE_SOURCEMAP = "false" 